config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/edit'
  get 'user/index'
  # get 'user/show'
  # get 'user/new'
  # get 'user/edit'
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :books

  # root 'books#index'

  # devise/sessions#new
  root :to => 'books#top'

  resources :books, only: [:new, :create, :index, :show]

  resource :book, only: [:new, :create, :index, :show, :destroy] do
     resource :favorites, only: [:create, :destry]
     resource :post_comments, only: [:create, :destroy]
  end

   resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	attachment :image

  # titleは必須 200字以内
  validates :book_title, presence: true
  # validates :book_body, length: { in: 1..200 }
  # bodyは必須　200字以内
  validates :book_body, presence: true
  validates :book_body, length: { in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
     #:名前がdeviseの機能名, :パスワードリセット, :ログイン情報を保存する
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	#nameを必須・一意とする
  validates_uniqueness_of :name
  validates_presence_of :name

  # nameは必須 200字以内
  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20, }

#nameを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["name = :value", { :value => name }]).first
    else
      where(conditions).first
    end
  end

  # captionは50字以内
  validates :caption, length: { maximum: 50 }



  # 登録時にemailを不要とする
  # def email_required?
  #   false
  # end

  # def email_changed?
  #   false
  # end


 	has_many :books
	attachment :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

  #ログインしないとどのページにも飛べないコード
  #ここに記入すると全てはじかれてしまう
   # before_action :authenticate_user!

   def after_sign_in_path_for(resource)
    # if resource_or_scope.is_a?(AdminUser)
      # admin_root_path
    # else
      user_path(resource)
   end

   def after_sign_out_path_for(resource)
      root_path
   end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	#ログインしないとどのページにも飛べないコード
   before_action :authenticate_user!, only: [:index, :show, :edit]

  def top
  end

  def index
  	@book = Book.new
  	@books = Book.all
  end

  def show
    @book_s = Book.new
  	@book = Book.find(params[:id])

  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
    else
      redirect_to books_path(@book)
    end
  end

  # def create
  #    @book = Book.new(book_params)
     # @book.user_id = current_user.id
  #    @book.save
  #    redirect_to book_path(@book)
  #  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'Bookers2 was successfully created.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render 'index'
    end
  end

  # def update
  #   book = Book.find(params[:id])
  #   book.update(book_params)
  #   redirect_to book_path(book)
  # end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
      flash[:notice] = 'Bookers2 was successfully created.'
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
  end

	private

    def user_params
        params.require(:user).permit(:caption, :image, :name)
    end

    def book_params
        params.require(:book).permit(:book_title, :book_body)
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	#ログインしないとどのページにも飛べないコード
   before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
  	@book = Book.new
  	@user = User.find(params[:id])
    @books = @user.books
    # @books = @user.books.page(params[:page])
  end

  def new

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else redirect_to user_path(current_user.id)
    end
  end

  # def update
  #   user = User.find(params[:id])
  #   user.update(user_params)
  #   redirect_to user_path(user)
  # end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
      flash[:notice] = 'Bookers2 was successfully created.'
      redirect_to user_path(@user.id)
      else
      render :edit
      end

  end

  def create
    user = User.new(user_params)
        user.save
        redirect_to user_path(user.id)
  end

  private

  def user_params
        params.require(:user).permit(:caption, :image, :name)
  end

    def book_params
        params.require(:book).permit(:book_title, :book_body, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_list_books.html.erb
<body>
 <div class="container">
  <div class="row">
   <div class="col-lg-3" style="">
   <h2>New books</h2>
   <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
   <% end %>
    <%= form_for(book) do |f| %>
    <div class="field">
     <label for="book_title">Title</label><br>
     <%= f.text_field :book_title, class: "book_title col-xs-12" %>
    </div>
    <div class="field">
    <label for="book_body">Opinion</label><br>
     <%= f.text_area :book_body, class: "book_body col-xs-12" %>
    </div>
    <div class="field">
     <%= f.submit 'Create Book', class: "book_#{book.id} btn btn-primary col-xs-12" %>
    </div>
    <% end %>
   </div>
  </div>
 </div>
</body>

app/views/books/about.html.erb
<div class='body'>
 <div class='container'>
  <p id="notice"></p>
  <div class="row">
   <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
   </div>
  </div>
 </div>
</div>
<footer>
 <div class='container'>
  <div class='row'>
   <div class='col-xs-3 col-xs-offset-9'>
    <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>

app/views/books/edit.html.erb
<body>
 <div class="container">
  <div class="row">
　 <div class="col-lg-6" style="">
   <h1>Editing Book</h1>
   <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
   <% end %>
   <%= form_for(@book) do |f| %>
   <h4>Title</h4>
   <%= f.text_field :book_title, class: "book_title" %>
   <h4>Opinion</h4>
   <%= f.text_field :book_body, class: "book_body" %>
   <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
   <% end %>
    <%= link_to "Show", book_path, class: "book_#{@book.id}" %>
    |
    <%= link_to "Back", books_path, class: "back" %>
    </div>
   </div>
  </div>
  <footer>
  <div class='container'>
   <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
 </footer>
</body>

app/views/books/index.html.erb
<body>
　<div class="container">
　　<div class="row">
　　　<div class="col-lg-3" style=""> 
      <%= render 'users/list_users', user: current_user %>
      <%= render 'books/list_books', book: @book %>
     </div>
     <div class="col-lg-9" style="">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
        </tr>
       </thead>
       <tbody>
       <% @books.each do |book| %>
       <tr>
       	<!-- attachment_image_tag(bookに紐ずけられているuser),写真-->
        <th><%= attachment_image_tag(book.user, :image, :fill, 50, 50, fallback: "noimage.png", class: "noimage") %></th>
        <td><%= link_to book.book_title, book_path(book.id), class: "book_#{book.id}" %></td>
        <td><%= book.book_body %></td>
       </tr>
       <% end %>
       </tbody>
      </table>
     </div>
    </div>
   </div>
  <footer>
  <div class='container'>
   <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
 </footer>
</body>

app/views/books/new.html.erb
<div class='body'>
 <div class='container'>
  <p id="notice"></p>
  <div class="row">
   <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
   </div>
  </div>
 </div>
</div>
<footer>
 <div class='container'>
  <div class='row'>
   <div class='col-xs-3 col-xs-offset-9'>
    <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>

app/views/books/show.html.erb
<body>
 <div class="container">
  <div class="row">
　  <div class="col-lg-3" style=""> 
     <%= render 'users/list_users', user: @book.user %>
     <div class="container">
      <div class="row">
       <div class="col-lg-3" style="">
       <h2>New books</h2>
       <% if @book.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
         <ul>
         <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
         </ul>
        </div>
         <% end %>
        <%= form_for(@book_s) do |f| %>
        <div class="field">
         <label for="book_title">Title</label><br>
         <%= f.text_field :book_title, class: "book_title col-xs-12" %>
        </div>
        <div class="field">
         <label for="book_body">Opinion</label><br>
         <%= f.text_area :book_body, class: "book_body col-xs-12" %>
        </div>
        <div class="field">
        <%= f.submit 'Create Book', class: "@book_#{@book_s.id} btn btn-primary col-xs-12" %>
        </div>
        <% end %>
       </div>
      </div>
     </div>
    </div>
    <div class="col-lg-9" style="">
     <h2>Book detail</h2>
     <table class="table">
      <tr><td><%= attachment_image_tag(@book.user, :image, :fill, 60, 60, class: "image") %><%= link_to user_path(@book.user_id) do %><br><%= @book.user.name %><% end %></td>
       <td><%= @book.book_title %></td>
       <td><%= @book.book_body %></td>
       <% if current_user.id == @book.user_id %>
       <td><%= link_to 'Edit', edit_book_path(@book.id), class: "edit_book_#{@book.id} btn btn-success active btn-sm" %></td>
       <td><%= link_to "Destroy", book_path(@book.id), class: "destroy_book_#{@book.id} btn btn-danger active btn-sm", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
       <% end %>
      </tr>
     </table>
    </div>
   </div>
  </div>
  <footer>
  <div class='container'>
   <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
 </footer>
</body>

app/views/books/top.html.erb
<div class='body'>
 <div class='container'>
  <p id="notice"></p>
  <div class="row">
   <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about varioius books!</p>
     <div class="btn-wrapper">
      <div class="row">
       <button type="button" class="btn btn-primary btn-block active btn btn-info">
       <%= link_to "Log in", new_user_session_path, class: "sign_in" %></button>
      </div>
      <div class="row">
       <button type="button" class="btn btn-primary btn-block active btn btn-success">
       <%= link_to "Sign Up", new_user_registration_path, class: "sign_up" %></button>
      </div>
     </div>
    </div>
   </div>
  </div>
</div>
<footer>
 <div class='container'>
  <div class='row'>
   <div class='col-xs-3 col-xs-offset-9'>
    <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">
        Bookers
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample7">
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
        <li><%= link_to 'Home', user_path(current_user.id), class: "home glyphicon glyphicon-home" %></li>
        <li><%= link_to 'Users', users_path, class: "users glyphicon glyphicon-user" %></li>
        <li><%= link_to 'Books', books_path, class: "books glyphicon glyphicon-book" %></li>
        <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "logout glyphicon glyphicon-log-out"  %></li>
       <% else %>
        <li><%= link_to "Home", root_path, class: "home glyphicon glyphicon-home" %></li>
        <li><%= link_to "About", new_book_path, class: "about glyphicon glyphicon-link" %></li>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "sign_up glyphicon glyphicon-edit" %></li >
        <li><%= link_to "Log in", new_user_session_path, class: "sign_in glyphicon glyphicon-log-in" %></li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<%= yield %>
</body>
</html>

app/views/users/_list_users.html.erb
<body>
 <div class="container">
  <div class="row">
   <div class="col-lg-3" style="">
    <h2>User info</h2>
    <%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "noimage.png" %>
     <table class="table">
      <tr>
       <th>name</th>
       <th><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.caption %></th>
      </tr>
     </table>
    <%= link_to "", edit_user_path(user), class: "edit_user_#{user.id} col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
   </div>
  </div>
 </div>
</body>

app/views/users/edit.html.erb
<body>
 <% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 <div class="container">
  <div class="row">
   <h2>User info</h2>
   <%= form_for(@user) do |f| %>
    <p>name</p>
    <%= f.text_field :name, class: "name" %>
    <p>Image</p>
    <%= f.attachment_field :image, class: "user_image", placeholder: "Image" %>
    <p>introduction</p>
    <%= f.text_area :caption, class: "introduction" %>
    <%= f.submit 'Update User' %>
   <% end %>
  </div>
 </div>
 <footer>
  <div class='container'>
   <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
 </footer>
</body>

app/views/users/index.html.erb
<body>
 <div class="container">
　<div class="row">
　　<div class="col-lg-3" style=""> 
     <%= render 'users/list_users', user: @user %>
     <%= render 'books/list_books', book: @book %>
    </div>
    <div class="col-lg-9" style="">
     <h2>Users</h2>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
      <tr>
       <!-- att_img_tag(bookに紐ずけられているuser),写真-->
       <td><%= attachment_image_tag user, :image, :fill, 50, 50, fallback: "noimage.png", class: "noimage" %></td>
       <td><%= user.name %></td>
       <td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
       <!-- ink_to user_path(@book.user_id) -->
       </tr>
      <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>
  <footer>
  <div class='container'>
   <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
 </footer>
</body>

app/views/users/new.html.erb
<html>
  <head>
    <h1>Books#new</h1>
    <title>Bookers</title>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
    	<div class="container">
    		<nav class='nav navbar-nav navbar-left' >
    			<span>Bookers</span>
            </nav>
            <nav>
            	<ul class="nav navbar-nav navbar-right">
            		<li><a class="glyphicon glyphicon-home" href="/"> Home</a></li>
                    <li><a class="glyphicon glyphicon-link" href="/home/about"> About</a></li>
                    <li><a class="glyphicon glyphicon-edit" href="/users/sign_up"> sign up</a></li>
                    <li><a class="glyphicon glyphicon-log-in" href="/users/sign_in"> login</a></li>
                </ul>
            </nav>
        </div>
    </header>

  	<div class='body'>
  		<div class='container'>
  			<p id="notice"></p>
  			<div class="row">
  				<div class='top-message col-md-offset-3 col-md-6'>
  					<h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
  						<p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
                        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                        <p> about varioius books!</p>
                        <div class="btn-wrapper">
                        	<div class="row">
                        		<%= link_to "Log in", "#" %>
                            </div>
                            <div class="row">
                            	<%= link_to "Sign in","#" %>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>

    <footer>
    	<div class='container'>
  	        <div class='row'>
  	        	<div class='col-xs-3 col-xs-offset-9'>
  	        		<p>CopyRight Infratop.inc</p>
    	        </div>
            </div>
        </div>
    </footer>


  </body>
</html>

app/views/users/show.html.erb
<body>
　<div class="container">
　　<div class="row">
　　　<div class="col-lg-3" style="">
      <%= render 'users/list_users', user: @user %>
      <%= render 'books/list_books', book: @book %>
     </div>
     <div class="col-lg-9" style="">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
        </tr>
       </thead>
       <tbody>
       <% @books.each do |book| %>
       <tr>
       	<!-- attachment_image_tag(bookに紐ずけられているuser),写真-->
        <th><%= attachment_image_tag(book.user, :image, :fill, 50, 50, fallback: "noimage.png", class: "noimage") %></th>
        <td><%=link_to book.book_title, book_path(book.id), class: "book_#{@book.id}" %></td>
        <td><%= book.book_body %></td>
       </tr>
       <% end %>
       </tbody>
      </table>
     </div>
    </div>
   </div>
 <footer>
  <div class='container'>
   <div class='row'>
    <div class='col-xs-3 col-xs-offset-9'>
     <p>CopyRight Infratop.inc</p>
    </div>
   </div>
  </div>
 </footer>
</body>